name: SSH Terminal with Root Access

on:
  workflow_dispatch:  # Manual trigger

jobs:
  ssh-access:
    runs-on: ubuntu-latest

    steps:
      - name: Install tmate
        run: |
          sudo apt update
          sudo apt install -y tmate

      - name: Start tmate session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "SSH Access (Public):"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "SSH Access (Web):"
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'

      - name: Keep session alive
        run: sleep 3600  # Keeps session active for 1 hour
