name: RDP with VNC + Root User + ngrok

on:
  workflow_dispatch:

jobs:
  rdp-vnc:
    runs-on: ubuntu-latest

    steps:
      - name: Install Desktop Environment & VNC Server
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver dbus-x11 x11-xserver-utils

      - name: Create Root User
        run: |
          sudo useradd -m -s /bin/bash user
          echo "user:rootpass" | sudo chpasswd
          echo "user ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/user
          sudo mkdir -p /home/user/.vnc
          echo "rootpass" | vncpasswd -f > /home/user/.vnc/passwd
          sudo chown -R user:user /home/user/.vnc
          sudo chmod 600 /home/user/.vnc/passwd

      - name: Kill Existing VNC Session (if any)
        run: |
          vncserver -kill :1 || true
          sudo pkill Xtightvnc || true

      - name: Fix Xauthority and Create xstartup Script
        run: |
          sudo -u user touch /home/user/.Xauthority
          sudo -u user mkdir -p /home/user/.vnc
          cat <<EOF | sudo -u user tee /home/user/.vnc/xstartup
          #!/bin/bash
          xrdb $HOME/.Xresources
          export XKL_XMODMAP_DISABLE=1
          export XDG_RUNTIME_DIR=/run/user/\$(id -u)
          export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/\$(id -u)/bus"
          startxfce4 &
          EOF
          sudo chmod +x /home/user/.vnc/xstartup

      - name: Start VNC Server as User
        run: |
          sudo -u user vncserver -kill :1 || true
          sudo -u user vncserver :1 -geometry 1280x720 -depth 24

      - name: Install ngrok & Start Tunnel
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok
          ngrok config add-authtoken 2P8v3I9oxTnCsnsVcKIOjd9Rt4Y_5jzoNH4hQQNfWcR8iQz8i
          nohup ngrok tcp 5901 > /dev/null 2>&1 &
          sleep 5  # Allow ngrok to start properly

      - name: Display ngrok VNC Address
        run: |
          sleep 5
          echo "Your VNC address:"
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep the session alive
        run: sleep 3600
