name: "GitHub RDP with VNC + Ngrok"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install XFCE & VNC
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver wget unzip

      - name: Set up VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "12345678" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          cat > ~/.vnc/xstartup <<EOF
          #!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &
          EOF
          chmod +x ~/.vnc/xstartup

          vncserver -kill :1 || true
          vncserver :1 -geometry 1024x768 -depth 24

      - name: Download & Install Ngrok
        run: |
          wget -q -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        run: |
          ngrok authtoken 2P8v3I9oxTnCsnsVcKIOjd9Rt4Y_5jzoNH4hQQNfWcR8iQz8i

      - name: Start Ngrok & Expose VNC
        run: |
          nohup ngrok tcp 5901 --log=stdout &>/dev/null &

      - name: Get Ngrok URL
        run: |
          sleep 5
          curl -s localhost:4040/api/tunnels | grep -o '"public_url":"tcp:[^"]*' | cut -d'"' -f4
          sleep 3000
