name: VS Code Server Access

on:
  workflow_dispatch:

jobs:
  vscode-access:
    runs-on: ubuntu-latest

    steps:
      - name: Install Code-Server
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh
          mkdir -p ~/.config/code-server
          echo "bind-addr: 0.0.0.0:8080" > ~/.config/code-server/config.yaml
          echo "auth: password" >> ~/.config/code-server/config.yaml
          echo "password: mysecretpassword" >> ~/.config/code-server/config.yaml
          echo "cert: false" >> ~/.config/code-server/config.yaml

      - name: Start VS Code Server
        run: |
          nohup code-server --bind-addr 0.0.0.0:8080 --auth password &
          sleep 10
          echo "VS Code is running at: http://$(curl -s ifconfig.me):8080"
          sleep 3600
