name: Setup RDP with CRD + XFCE4

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest

    steps:
      - name: Update & Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget sudo curl software-properties-common

      - name: Create User and Setup
        env:
          USERNAME: ${{ secrets.RDP_USERNAME }}
          PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          sudo useradd -m -s /bin/bash "$USERNAME"
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo "$USERNAME"
          sudo mkdir -p /home/$USERNAME/.local/bin
          echo 'export PATH=$PATH:/home/$USERNAME/.local/bin' | sudo tee -a /home/$USERNAME/.bashrc
          sudo chown -R $USERNAME:$USERNAME /home/$USERNAME

      - name: Install Desktop & CRD
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt install -fy
          echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session
          sudo systemctl disable lightdm.service
          sudo apt install -y xscreensaver dbus-x11
          sudo usermod -aG chrome-remote-desktop $USERNAME

      - name: Setup Storage
        run: |
          sudo mkdir -p /storage
          sudo chmod 777 /storage
          sudo chown "$USERNAME":"$USERNAME" /storage
          sudo mkdir -p /home/"$USERNAME"/storage
          sudo mount --bind /storage /home/"$USERNAME"/storage

      - name: Install CRD Session & Run
        env:
          CRD_COMMAND: ${{ secrets.CRD_COMMAND }}
          PIN: ${{ secrets.CRD_PIN }}
          USERNAME: ${{ secrets.RDP_USERNAME }}
        run: |
          su - "$USERNAME" -c "$CRD_COMMAND --pin=$PIN"
          sudo service chrome-remote-desktop start

      - name: Keep Session Alive
        run: |
          while true; do echo "I'm alive"; sleep 300; done
