name: Install 3x-UI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Installation Script with Automated Input and Root Privileges
        run: |
          echo -e "no\n" | sudo bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) | tee output.log
          cat output.log | grep -oP 'http[s]?://[^ ]+' > extracted_url.txt

      - name: Display Extracted URL
        run: cat extracted_url.txt
